# This is a basic workflow to help you get started with Actions

name: Salesforce Github Integration 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ githubActionTest ]
#  push:
#    branches: [ githubActionTest ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: 'Build and Deploy'
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install
 # Runs a set of commands using the runners shell
    - name: 'Populate auth file with SFDX_URL Secret'
      run : 'echo "${{ secrets.SFDX_DEVHUB_URL }}" > /home/runner/work/authFile.json;cat /home/runner/work/authFile.json'
      shell: bash
    - name: 'Environment Variable Assign'
      env:
        HUB_ORG_USER: ${{ secrets.HUB_ORG_DEVHUB }}
      run: 'echo $HUB_ORG_USER'
    - name: 'Authenticate against Dev Hub org'
      run: sfdx force:auth:sfdxurl:store -f /home/runner/work/authFile.json -d -a DevHubOrg --setdefaultdevhubusername 
    - name: 'Create scratch org'
      run: sfdx force:org:create -f config/project-scratch-def.json --setalias my_scratch --durationdays 7 --setdefaultusername --json --loglevel fatal
    - name: 'Push source'
#      run: sfdx force:source:deploy -p force-app -u my_scratch --testlevel RunLocalTests -c
      run: sfdx force:source:push -u my_scratch
    - name: 'List orgs'
      run: sfdx force:org:list
    - name: Run Apex Test
      run: sfdx force:apex:test:run -l RunLocalTests --resultformat tap --codecoverage -c -u my_scratch
 #     run: sfdx force:apex:test:run --resultformat tap --codecoverage -c -r human
    - name: Delete scratch org
      run: 'sfdx force:org:delete -u my_scratch --noprompt'
  auto-approve:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
